### ISSUE TITLE
TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by eric-grab** [dvdciri/daggraph#40] opened 2018-04-02 02:43 UTC
### Description
I ran `daggraph` in my Android project root folder and got:
```
? What kind of chart do you want to generate? Bubble chart
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:1239:7)
    at createFileAndSave (/usr/local/lib/node_modules/daggraph/src/router.js:136:28)
    at fileDataPromise.then (/usr/local/lib/node_modules/daggraph/src/router.js:64:42)
    at <anonymous>
```

### Steps to reproduce
Execute `daggraph`
Select a chart type
### Expected behaviour
See the chart

**Comment by tharoldD** [comment] 2018-04-02 03:40
probably a duplicate of [#39](https://github.com/dvdciri/daggraph/issues/39),
got this issue too after upgrade to version 0.3.0.
what version of daggraph are you running?

**Comment by dvdciri** [comment] 2018-04-02 16:00
Thanks for reporting this. It's definitely a bug and i've opened a PR to fix this. #41 
Closing as duplicate

**Closed as completed by dvdciri** 2018-04-02 16:00 UTC
